<?php $title = $title ?? 'Certificate of Origin'; $action = $action ?? '/certificate-of-origins'; $certificate = $certificate ?? null; $meta = $meta ?? []; $items = $items ?? [[]]; $buyers = $buyers ?? []; $currencies = $currencies ?? []; $products = $products ?? []; $statuses = $statuses ?? []; ?>
<div class="page-header"><h1><?= escapeHtml($title) ?></h1><a href="/certificate-of-origins" class="btn btn-outline-secondary">Back</a></div>
<div class="card"><div class="card-body"><form method="post" action="<?= escapeHtml($action) ?>" class="needs-validation" novalidate><?= csrfToken() ?>
<div class="row"><div class="col-md-3 mb-3"><label class="form-label">Buyer</label><select name="buyer_id" class="form-select" required><option value="0">Select Buyer</option><?php foreach ($buyers as $buyer): ?><option value="<?= (int) $buyer['id'] ?>" <?= (int) ($certificate['buyer_id'] ?? 0) === (int) $buyer['id'] ? 'selected' : '' ?>><?= escapeHtml($buyer['company_name']) ?></option><?php endforeach; ?></select></div><div class="col-md-3 mb-3"><label class="form-label">Currency</label><select name="currency_id" class="form-select" data-master="currencies" data-master-title="Currency" required><option value="0">Select</option><?php foreach ($currencies as $currency): ?><option value="<?= (int) $currency['id'] ?>" <?= (int) ($certificate['currency_id'] ?? 0) === (int) $currency['id'] ? 'selected' : '' ?>><?= escapeHtml($currency['code']) ?></option><?php endforeach; ?></select></div></div>
<div class="row"><div class="col-md-3 mb-3"><label class="form-label">Status</label><select name="status" class="form-select"><?php foreach ($statuses as $statusId => $statusName): ?><option value="<?= (int) $statusId ?>" <?= (int) ($certificate['status'] ?? 0) === (int) $statusId ? 'selected' : '' ?>><?= escapeHtml($statusName) ?></option><?php endforeach; ?></select></div><div class="col-md-3 mb-3"><label class="form-label">Issuing Authority</label><input name="issuing_authority" class="form-control" value="<?= escapeHtml($meta['issuing_authority'] ?? '') ?>"></div><div class="col-md-3 mb-3"><label class="form-label">Country of Origin</label><input name="country_of_origin" class="form-control" value="<?= escapeHtml($meta['country_of_origin'] ?? '') ?>"></div><div class="col-md-3 mb-3"><label class="form-label">Destination Country</label><input name="destination_country" class="form-control" value="<?= escapeHtml($meta['destination_country'] ?? '') ?>"></div></div>
<div class="row"><div class="col-md-3 mb-3"><label class="form-label">HS Code</label><select name="hs_code" class="form-select" data-master="hs-codes" data-master-title="HS Code"><option value="<?= escapeHtml($meta['hs_code'] ?? '') ?>"><?= escapeHtml($meta['hs_code'] ?? 'Select') ?></option></select></div><div class="col-md-3 mb-3"><label class="form-label">Exporter</label><input name="exporter" class="form-control" value="<?= escapeHtml($meta['exporter'] ?? '') ?>"></div><div class="col-md-3 mb-3"><label class="form-label">Consignee</label><input name="consignee" class="form-control" value="<?= escapeHtml($meta['consignee'] ?? '') ?>"></div><div class="col-md-3 mb-3"><label class="form-label">Revision</label><input type="number" name="revision" class="form-control" value="<?= (int) ($meta['revision'] ?? 0) ?>"></div></div>
<div class="mb-3"><label class="form-label">Declaration</label><textarea name="declaration" class="form-control" rows="3"><?= escapeHtml($meta['declaration'] ?? '') ?></textarea></div>
<h5>Products</h5><div class="table-responsive"><table class="table table-bordered"><thead><tr><th>Product</th><th>HS Code</th><th>Quantity</th><th>Remarks</th></tr></thead><tbody><?php for ($i = 0; $i < 5; $i++): $item = $items[$i] ?? []; ?><tr><td><select name="product_id[]" class="form-select"><option value="0">Product</option><?php foreach ($products as $product): ?><option value="<?= (int) $product['id'] ?>" <?= (int) ($item['product_id'] ?? 0) === (int) $product['id'] ? 'selected' : '' ?>><?= escapeHtml($product['name']) ?></option><?php endforeach; ?></select></td><td><select name="hsn_code[]" class="form-select" data-master="hs-codes" data-master-title="HS Code"><option value="<?= escapeHtml($item['hsn_code'] ?? '') ?>"><?= escapeHtml($item['hsn_code'] ?? 'HS Code') ?></option></select></td><td><input name="quantity[]" class="form-control" value="<?= escapeHtml($item['quantity'] ?? '') ?>"></td><td><input name="item_remarks[]" class="form-control" value=""></td></tr><?php endfor; ?></tbody></table></div>
<div class="mb-3"><label class="form-label">Remarks</label><textarea name="remarks" class="form-control" rows="3"><?= escapeHtml($certificate['remarks'] ?? '') ?></textarea></div><button class="btn btn-primary">Save Certificate</button>
</form></div></div>