<?php
$filters = $filters ?? [];
$buyers = $buyers ?? [];
$products = $products ?? [];
$currencies = $currencies ?? [];
$summary = $summary ?? [];
$exportMode = $exportMode ?? '';
?>
<style>@media print {.no-print{display:none!important}.card{border:0}}</style>
<div class="page-header no-print"><h1>Reports & Analytics</h1><div class="btn-group"><a class="btn btn-outline-secondary" href="/reports?<?= http_build_query(array_merge($filters, ['export' => 'pdf'])) ?>">PDF Ready</a><a class="btn btn-outline-success" href="/reports?<?= http_build_query(array_merge($filters, ['export' => 'excel'])) ?>">Excel Ready</a><button onclick="window.print()" class="btn btn-outline-dark">Print Ready</button></div></div>
<div class="card mb-3 no-print"><div class="card-body"><form method="get" action="/reports" class="row g-3"><div class="col-md-2"><label class="form-label">Date From</label><input type="date" name="date_from" class="form-control" value="<?= escapeHtml($filters['date_from'] ?? '') ?>"></div><div class="col-md-2"><label class="form-label">Date To</label><input type="date" name="date_to" class="form-control" value="<?= escapeHtml($filters['date_to'] ?? '') ?>"></div><div class="col-md-2"><label class="form-label">Buyer</label><select name="buyer_id" class="form-select"><option value="0">All</option><?php foreach ($buyers as $buyer): ?><option value="<?= (int) $buyer['id'] ?>" <?= (int) ($filters['buyer_id'] ?? 0) === (int) $buyer['id'] ? 'selected' : '' ?>><?= escapeHtml($buyer['company_name']) ?></option><?php endforeach; ?></select></div><div class="col-md-2"><label class="form-label">Country</label><input name="country" class="form-control" value="<?= escapeHtml($filters['country'] ?? '') ?>"></div><div class="col-md-2"><label class="form-label">Product</label><select name="product_id" class="form-select"><option value="0">All</option><?php foreach ($products as $product): ?><option value="<?= (int) $product['id'] ?>" <?= (int) ($filters['product_id'] ?? 0) === (int) $product['id'] ? 'selected' : '' ?>><?= escapeHtml($product['name']) ?></option><?php endforeach; ?></select></div><div class="col-md-1"><label class="form-label">Status</label><input name="status" class="form-control" value="<?= escapeHtml($filters['status'] ?? '') ?>"></div><div class="col-md-1"><label class="form-label">Currency</label><select name="currency_id" class="form-select"><option value="0">All</option><?php foreach ($currencies as $currency): ?><option value="<?= (int) $currency['id'] ?>" <?= (int) ($filters['currency_id'] ?? 0) === (int) $currency['id'] ? 'selected' : '' ?>><?= escapeHtml($currency['code']) ?></option><?php endforeach; ?></select></div><div class="col-md-12"><button class="btn btn-primary">Apply Filters</button><a href="/reports" class="btn btn-outline-secondary">Reset</a></div></form></div></div>
<?php if ($exportMode !== ''): ?><div class="alert alert-info">Export mode: <?= escapeHtml(strtoupper($exportMode)) ?> ready layout.</div><?php endif; ?>
<?php foreach ($summary as $reportName => $report): ?>
    <div class="card mb-3"><div class="card-header d-flex justify-content-between"><strong><?= escapeHtml($reportName) ?></strong><span><?= (int) $report['count'] ?> records</span></div><div class="card-body"><div class="table-responsive"><table class="table table-sm table-striped"><thead><tr><th>Reference</th><th>Date</th><th>Type / Title</th><th>Buyer / Category</th><th>Status</th><th>Quantity</th><th>Amount</th></tr></thead><tbody><?php foreach ($report['rows'] as $row): ?><tr><td><?= escapeHtml($row['reference_no'] ?? '') ?></td><td><?= escapeHtml((string) ($row['report_date'] ?? $row['created_at'] ?? '')) ?></td><td><?= escapeHtml($row['document_type'] ?? $row['title'] ?? '') ?></td><td><?= escapeHtml($row['buyer_name'] ?? $row['category'] ?? '') ?></td><td><?= escapeHtml((string) ($row['status'] ?? '')) ?></td><td class="text-end"><?= number_format((float) ($row['quantity'] ?? $row['document_count'] ?? 0), 3) ?></td><td class="text-end"><?= number_format((float) ($row['amount'] ?? 0), 2) ?></td></tr><?php endforeach; ?></tbody></table></div></div></div>
<?php endforeach; ?>