<?php
$packingLists = $packingLists ?? [];
$statuses = $statuses ?? [];
$search = $search ?? '';
$status = $status ?? '';
$statusClasses = [0 => 'bg-secondary', 2 => 'bg-success', 4 => 'bg-info', 5 => 'bg-primary', 6 => 'bg-danger'];
?>
<div class="page-header"><h1>Packing Lists</h1><a href="/packing-lists/create" class="btn btn-primary">Create Packing List</a></div>
<div class="card mb-3"><div class="card-body"><form method="get" action="/packing-lists" class="row g-3"><div class="col-md-6"><label class="form-label" for="search">Packing List Search</label><input type="text" id="search" name="search" class="form-control" value="<?= escapeHtml($search) ?>" placeholder="PL number, buyer or remarks"></div><div class="col-md-3"><label class="form-label" for="status">Status</label><select id="status" name="status" class="form-select"><option value="" <?= $status === '' ? 'selected' : '' ?>>All</option><?php foreach ($statuses as $statusId => $statusName): ?><option value="<?= (int) $statusId ?>" <?= (string) $status === (string) $statusId ? 'selected' : '' ?>><?= escapeHtml($statusName) ?></option><?php endforeach; ?></select></div><div class="col-md-3 d-flex align-items-end gap-2"><button type="submit" class="btn btn-primary">Search</button><a href="/packing-lists" class="btn btn-outline-secondary">Reset</a></div></form></div></div>
<div class="card"><div class="card-body"><div class="table-responsive"><table class="table table-striped datatable"><thead><tr><th>PL No.</th><th>Date</th><th>Buyer</th><th>Currency</th><th>Status</th><th>Actions</th></tr></thead><tbody><?php foreach ($packingLists as $packingList): ?><tr><td><?= escapeHtml($packingList['document_number']) ?></td><td><?= escapeHtml($packingList['document_date']) ?></td><td><?= escapeHtml($packingList['buyer_name'] ?? '') ?></td><td><?= escapeHtml($packingList['currency_code'] ?? '') ?></td><td><span class="badge <?= escapeHtml($statusClasses[(int) $packingList['status']] ?? 'bg-secondary') ?>"><?= escapeHtml($statuses[(int) $packingList['status']] ?? 'Unknown') ?></span></td><td><a href="/packing-lists/<?= (int) $packingList['id'] ?>" class="btn btn-sm btn-outline-secondary">View</a> <a href="/packing-lists/<?= (int) $packingList['id'] ?>/edit" class="btn btn-sm btn-outline-primary">Edit</a> <a href="/packing-lists/<?= (int) $packingList['id'] ?>/print" class="btn btn-sm btn-outline-dark">Print</a></td></tr><?php endforeach; ?></tbody></table></div></div></div>