<?php
$quotation = $packingList ?? [];
$meta = $meta ?? [];
$items = $items ?? [];
$statuses = $statuses ?? [];
$revisions = $revisions ?? [];
$history = $history ?? [];
$statusClasses = [0 => 'bg-secondary', 2 => 'bg-success', 4 => 'bg-info', 5 => 'bg-primary', 6 => 'bg-danger'];
?>
<style>@media print {.no-print{display:none!important}.card{border:0}.page-header{display:none}}</style>
<div class="page-header no-print"><h1><?= escapeHtml($quotation['document_number'] ?? '') ?></h1><div class="btn-group"><a href="/packing-lists" class="btn btn-outline-secondary">Back</a><a href="/packing-lists/<?= (int) ($quotation['id'] ?? 0) ?>/edit" class="btn btn-outline-primary">Edit</a><button onclick="window.print()" class="btn btn-outline-dark">Print</button></div></div>
<div class="card"><div class="card-body"><div class="text-center mb-4"><h2>PACKING LIST</h2><div class="text-muted">Print Ready</div></div><div class="row mb-3"><div class="col-md-6"><strong>PL No:</strong> <?= escapeHtml($quotation['document_number'] ?? '') ?><br><strong>Revision:</strong> <?= (int) ($meta['revision'] ?? 0) ?><br><strong>Date:</strong> <?= escapeHtml($quotation['document_date'] ?? '') ?><br><strong>Status:</strong> <span class="badge <?= escapeHtml($statusClasses[(int) ($quotation['status'] ?? 0)] ?? 'bg-secondary') ?>"><?= escapeHtml($statuses[(int) ($quotation['status'] ?? 0)] ?? 'Unknown') ?></span></div><div class="col-md-6"><strong>Buyer:</strong> <?= escapeHtml($quotation['buyer_name'] ?? '') ?><br><strong>Currency:</strong> <?= escapeHtml($quotation['currency_code'] ?? '') ?><br><strong>Loading Port:</strong> <?= escapeHtml($quotation['loading_port_name'] ?? '') ?><br><strong>Destination Port:</strong> <?= escapeHtml($quotation['delivery_port_name'] ?? '') ?></div></div><div class="table-responsive"><table class="table table-bordered"><thead><tr><th>#</th><th>Product</th><th>HS Code</th><th>Packaging</th><th>Quantity</th><th>Unit</th><th>Remarks</th></tr></thead><tbody><?php foreach ($items as $index => $item): ?><tr><td><?= $index + 1 ?></td><td><?= escapeHtml($item['product_name'] ?? '') ?></td><td><?= escapeHtml($item['hsn_code'] ?? '') ?></td><td><?= escapeHtml($item['packing_type_name'] ?? '') ?></td><td class="text-end"><?= number_format((float) ($item['quantity'] ?? 0), 3) ?></td><td><?= escapeHtml($item['unit_code'] ?? '') ?></td><td></td></tr><?php endforeach; ?></tbody></table></div><div><strong>Remarks:</strong><br><?= nl2br(escapeHtml($quotation['remarks'] ?? '')) ?></div></div></div>
<div class="row mt-3 no-print"><div class="col-md-6"><div class="card"><div class="card-body"><h5>Revision History</h5><?php foreach ($revisions as $revision): ?><div>Rev <?= (int) $revision['revision_number'] ?> - <?= escapeHtml($revision['created_at']) ?> - <?= escapeHtml($revision['revision_notes'] ?? '') ?></div><?php endforeach; ?><form method="post" action="/packing-lists/<?= (int) ($quotation['id'] ?? 0) ?>/revise" class="mt-2"><?= csrfToken() ?><input type="text" name="revision_notes" class="form-control mb-2" placeholder="Revision notes"><button class="btn btn-sm btn-primary">Save Revision</button></form></div></div></div><div class="col-md-6"><div class="card"><div class="card-body"><h5>Status Workflow</h5><form method="post" action="/packing-lists/<?= (int) ($quotation['id'] ?? 0) ?>/status" class="row g-2"><?= csrfToken() ?><div class="col-md-5"><select name="status" class="form-select"><?php foreach ($statuses as $statusId => $statusName): ?><option value="<?= (int) $statusId ?>" <?= (int) ($quotation['status'] ?? 0) === (int) $statusId ? 'selected' : '' ?>><?= escapeHtml($statusName) ?></option><?php endforeach; ?></select></div><div class="col-md-5"><input type="text" name="remarks" class="form-control" placeholder="Status remarks"></div><div class="col-md-2"><button class="btn btn-primary">Update</button></div></form><?php foreach ($history as $entry): ?><div class="small text-muted mt-1"><?= escapeHtml($entry['created_at']) ?>: <?= escapeHtml($statuses[(int) $entry['new_status']] ?? 'Unknown') ?> <?= escapeHtml($entry['remarks'] ?? '') ?></div><?php endforeach; ?></div></div></div></div>