<?php
$title = $title ?? 'Shipping Bill';
$action = $action ?? '/shipping-bills';
$shippingBill = $shippingBill ?? null;
$meta = $meta ?? [];
$items = $items ?? [[]];
$buyers = $buyers ?? [];
$currencies = $currencies ?? [];
$incoterms = $incoterms ?? [];
$paymentTerms = $paymentTerms ?? [];
$ports = $ports ?? [];
$products = $products ?? [];
$packingTypes = $packingTypes ?? [];
$statuses = $statuses ?? [];
?>
<div class="page-header"><h1><?= escapeHtml($title) ?></h1><a href="/shipping-bills" class="btn btn-outline-secondary">Back</a></div>
<div class="card"><div class="card-body"><form method="post" action="<?= escapeHtml($action) ?>" class="needs-validation" novalidate><?= csrfToken() ?>
<h5 class="mb-3">Shipping Bill Header</h5><div class="row"><div class="col-md-3 mb-3"><label class="form-label">Shipping Bill No</label><input name="shipping_bill_no" class="form-control" value="<?= escapeHtml($meta['shipping_bill_no'] ?? ($shippingBill['document_number'] ?? 'Auto')) ?>"></div><div class="col-md-3 mb-3"><label class="form-label">Shipping Bill Date</label><input type="date" name="shipping_bill_date" class="form-control" value="<?= escapeHtml($meta['shipping_bill_date'] ?? ($shippingBill['document_date'] ?? date('Y-m-d'))) ?>"></div><div class="col-md-3 mb-3"><label class="form-label">Document Date</label><input type="date" name="document_date" class="form-control" value="<?= escapeHtml($shippingBill['document_date'] ?? date('Y-m-d')) ?>" required></div><div class="col-md-3 mb-3"><label class="form-label">Status</label><select name="status" class="form-select"><?php foreach ($statuses as $statusId => $statusName): ?><option value="<?= (int) $statusId ?>" <?= (int) ($shippingBill['status'] ?? 0) === (int) $statusId ? 'selected' : '' ?>><?= escapeHtml($statusName) ?></option><?php endforeach; ?></select></div></div>
<div class="row"><div class="col-md-4 mb-3"><label class="form-label">Buyer</label><select name="buyer_id" class="form-select" required><option value="0">Select Buyer</option><?php foreach ($buyers as $buyer): ?><option value="<?= (int) $buyer['id'] ?>" <?= (int) ($shippingBill['buyer_id'] ?? 0) === (int) $buyer['id'] ? 'selected' : '' ?>><?= escapeHtml($buyer['company_name']) ?></option><?php endforeach; ?></select></div><div class="col-md-4 mb-3"><label class="form-label">Currency</label><select name="currency_id" class="form-select" data-master="currencies" data-master-title="Currency" required><option value="0">Select</option><?php foreach ($currencies as $currency): ?><option value="<?= (int) $currency['id'] ?>" <?= (int) ($shippingBill['currency_id'] ?? 0) === (int) $currency['id'] ? 'selected' : '' ?>><?= escapeHtml($currency['code']) ?></option><?php endforeach; ?></select></div><div class="col-md-4 mb-3"><label class="form-label">Port</label><select name="port" class="form-select" data-master="ports" data-master-title="Port"><option value="<?= escapeHtml($meta['port'] ?? '') ?>"><?= escapeHtml($meta['port'] ?? 'Select') ?></option></select></div></div>
<div class="row"><div class="col-md-3 mb-3"><label class="form-label">Loading Port</label><select name="loading_port_id" class="form-select" data-master="ports" data-master-title="Port"><option value="0">Select</option><?php foreach ($ports as $port): ?><option value="<?= (int) $port['id'] ?>" <?= (int) ($shippingBill['loading_port_id'] ?? 0) === (int) $port['id'] ? 'selected' : '' ?>><?= escapeHtml($port['name']) ?></option><?php endforeach; ?></select></div><div class="col-md-3 mb-3"><label class="form-label">Destination Port</label><select name="delivery_port_id" class="form-select" data-master="ports" data-master-title="Port"><option value="0">Select</option><?php foreach ($ports as $port): ?><option value="<?= (int) $port['id'] ?>" <?= (int) ($shippingBill['destination_port_id'] ?? 0) === (int) $port['id'] ? 'selected' : '' ?>><?= escapeHtml($port['name']) ?></option><?php endforeach; ?></select></div><div class="col-md-3 mb-3"><label class="form-label">CHA</label><input name="cha" class="form-control" value="<?= escapeHtml($meta['cha'] ?? '') ?>"></div><div class="col-md-3 mb-3"><label class="form-label">Custom House</label><input name="custom_house" class="form-control" value="<?= escapeHtml($meta['custom_house'] ?? '') ?>"></div></div>
<div class="row"><div class="col-md-3 mb-3"><label class="form-label">Container Details</label><select name="container_details" class="form-select" data-master="container-types" data-master-title="Container Type"><option value="<?= escapeHtml($meta['container_details'] ?? '') ?>"><?= escapeHtml($meta['container_details'] ?? 'Select') ?></option></select></div><div class="col-md-3 mb-3"><label class="form-label">LEO</label><input name="leo" class="form-control" value="<?= escapeHtml($meta['leo'] ?? '') ?>"></div><div class="col-md-3 mb-3"><label class="form-label">Drawback</label><input name="drawback" class="form-control" value="<?= escapeHtml($meta['drawback'] ?? '') ?>"></div><div class="col-md-3 mb-3"><label class="form-label">Scheme</label><input name="scheme" class="form-control" value="<?= escapeHtml($meta['scheme'] ?? '') ?>"></div></div>
<div class="mb-3"><label class="form-label">Exporter Details</label><textarea name="exporter_details" class="form-control" rows="2"><?= escapeHtml($meta['exporter_details'] ?? '') ?></textarea></div>
<h5 class="mt-4 mb-3">Container / Product Details</h5><div class="table-responsive"><table class="table table-bordered"><thead><tr><th>Product</th><th>HS Code</th><th>Package Type</th><th>Quantity</th><th>Net Weight</th><th>Gross Weight</th><th>Remarks</th></tr></thead><tbody><?php for ($i = 0; $i < 6; $i++): $item = $items[$i] ?? []; ?><tr><td><select name="product_id[]" class="form-select form-select-sm"><option value="0">Product</option><?php foreach ($products as $product): ?><option value="<?= (int) $product['id'] ?>" <?= (int) ($item['product_id'] ?? 0) === (int) $product['id'] ? 'selected' : '' ?>><?= escapeHtml($product['name']) ?></option><?php endforeach; ?></select></td><td><select name="hsn_code[]" class="form-select form-select-sm" data-master="hs-codes" data-master-title="HS Code"><option value="<?= escapeHtml($item['hsn_code'] ?? '') ?>"><?= escapeHtml($item['hsn_code'] ?? 'HS Code') ?></option></select></td><td><select name="packing_type_id[]" class="form-select form-select-sm" data-master="packing-types" data-master-title="Packaging Type"><option value="0">Type</option><?php foreach ($packingTypes as $type): ?><option value="<?= (int) $type['id'] ?>" <?= (int) ($item['packing_type_id'] ?? 0) === (int) $type['id'] ? 'selected' : '' ?>><?= escapeHtml($type['name']) ?></option><?php endforeach; ?></select></td><td><input name="quantity[]" class="form-control form-control-sm" value="<?= escapeHtml($item['quantity'] ?? '') ?>"></td><td><input name="net_weight[]" class="form-control form-control-sm" value="<?= escapeHtml($item['net_weight'] ?? '') ?>"></td><td><input name="gross_weight[]" class="form-control form-control-sm" value="<?= escapeHtml($item['gross_weight'] ?? '') ?>"></td><td><input name="item_remarks[]" class="form-control form-control-sm" value="<?= escapeHtml($item['item_remarks'] ?? '') ?>"></td></tr><?php endfor; ?></tbody></table></div>
<div class="mb-3"><label class="form-label">Remarks</label><textarea name="remarks" class="form-control" rows="3"><?= escapeHtml($shippingBill['remarks'] ?? '') ?></textarea></div><input type="hidden" name="valid_until" value=""><input type="hidden" name="freight" value="0"><input type="hidden" name="insurance" value="0"><input type="hidden" name="other_charges" value="0"><button class="btn btn-primary">Save Shipping Bill</button>
</form></div></div>