<?php
$shippingBills = $shippingBills ?? [];
$statuses = $statuses ?? [];
$search = $search ?? '';
$status = $status ?? '';
$statusClasses = [0 => 'bg-secondary', 1 => 'bg-warning', 2 => 'bg-info', 3 => 'bg-primary', 5 => 'bg-success', 6 => 'bg-danger'];
?>
<div class="page-header"><h1>Shipping Bills</h1><a href="/shipping-bills/create" class="btn btn-primary">Create Shipping Bill</a></div>
<div class="card mb-3"><div class="card-body"><form method="get" action="/shipping-bills" class="row g-3"><div class="col-md-6"><label class="form-label">Search</label><input name="search" class="form-control" value="<?= escapeHtml($search) ?>" placeholder="Shipping Bill, buyer or remarks"></div><div class="col-md-3"><label class="form-label">Status</label><select name="status" class="form-select"><option value="" <?= $status === '' ? 'selected' : '' ?>>All</option><?php foreach ($statuses as $statusId => $statusName): ?><option value="<?= (int) $statusId ?>" <?= (string) $status === (string) $statusId ? 'selected' : '' ?>><?= escapeHtml($statusName) ?></option><?php endforeach; ?></select></div><div class="col-md-3 d-flex align-items-end gap-2"><button class="btn btn-primary">Search</button><a href="/shipping-bills" class="btn btn-outline-secondary">Reset</a></div></form></div></div>
<div class="card"><div class="card-body"><div class="table-responsive"><table class="table table-striped datatable"><thead><tr><th>Shipping Bill No</th><th>Date</th><th>Buyer</th><th>Status</th><th>Actions</th></tr></thead><tbody><?php foreach ($shippingBills as $bill): ?><tr><td><?= escapeHtml($bill['document_number']) ?></td><td><?= escapeHtml($bill['document_date']) ?></td><td><?= escapeHtml($bill['buyer_name'] ?? '') ?></td><td><span class="badge <?= escapeHtml($statusClasses[(int) $bill['status']] ?? 'bg-secondary') ?>"><?= escapeHtml($statuses[(int) $bill['status']] ?? 'Unknown') ?></span></td><td><a href="/shipping-bills/<?= (int) $bill['id'] ?>" class="btn btn-sm btn-outline-secondary">View</a> <a href="/shipping-bills/<?= (int) $bill['id'] ?>/edit" class="btn btn-sm btn-outline-primary">Edit</a> <a href="/shipping-bills/<?= (int) $bill['id'] ?>/print" class="btn btn-sm btn-outline-dark">Print</a></td></tr><?php endforeach; ?></tbody></table></div></div></div>