<?php
$shippingBill = $shippingBill ?? [];
$meta = $meta ?? [];
$items = $items ?? [];
$statuses = $statuses ?? [];
$revisions = $revisions ?? [];
$history = $history ?? [];
$statusClasses = [0 => 'bg-secondary', 1 => 'bg-warning', 2 => 'bg-info', 3 => 'bg-primary', 5 => 'bg-success', 6 => 'bg-danger'];
?>
<style>@media print {.no-print{display:none!important}.card{border:0}.page-header{display:none}}</style>
<div class="page-header no-print"><h1><?= escapeHtml($shippingBill['document_number'] ?? '') ?></h1><div class="btn-group"><a href="/shipping-bills" class="btn btn-outline-secondary">Back</a><a href="/shipping-bills/<?= (int) ($shippingBill['id'] ?? 0) ?>/edit" class="btn btn-outline-primary">Edit</a><button onclick="window.print()" class="btn btn-outline-dark">Print</button><form method="post" action="/shipping-bills/<?= (int) ($shippingBill['id'] ?? 0) ?>/email" class="d-inline"><?= csrfToken() ?><button class="btn btn-outline-info">Email Ready</button></form><form method="post" action="/shipping-bills/<?= (int) ($shippingBill['id'] ?? 0) ?>/convert" class="d-inline" onsubmit="return confirm('Convert Shipping Bill to Bill of Lading?');"><?= csrfToken() ?><button class="btn btn-success">Convert to BL</button></form></div></div>
<div class="card"><div class="card-body"><div class="text-center mb-4"><h2>SHIPPING BILL</h2><div class="text-muted">Print Ready</div></div><div class="row mb-3"><div class="col-md-6"><strong>Shipping Bill No:</strong> <?= escapeHtml($meta['shipping_bill_no'] ?? ($shippingBill['document_number'] ?? '')) ?><br><strong>Shipping Bill Date:</strong> <?= escapeHtml($meta['shipping_bill_date'] ?? ($shippingBill['document_date'] ?? '')) ?><br><strong>Status:</strong> <span class="badge <?= escapeHtml($statusClasses[(int) ($shippingBill['status'] ?? 0)] ?? 'bg-secondary') ?>"><?= escapeHtml($statuses[(int) ($shippingBill['status'] ?? 0)] ?? 'Unknown') ?></span><br><strong>Buyer:</strong> <?= escapeHtml($shippingBill['buyer_name'] ?? '') ?></div><div class="col-md-6"><strong>Port:</strong> <?= escapeHtml($meta['port'] ?? '') ?><br><strong>CHA:</strong> <?= escapeHtml($meta['cha'] ?? '') ?><br><strong>Custom House:</strong> <?= escapeHtml($meta['custom_house'] ?? '') ?><br><strong>Container Details:</strong> <?= escapeHtml($meta['container_details'] ?? '') ?></div></div><div class="row mb-3"><div class="col-md-3"><strong>LEO:</strong> <?= escapeHtml($meta['leo'] ?? '') ?></div><div class="col-md-3"><strong>Drawback:</strong> <?= escapeHtml($meta['drawback'] ?? '') ?></div><div class="col-md-3"><strong>Scheme:</strong> <?= escapeHtml($meta['scheme'] ?? '') ?></div><div class="col-md-3"><strong>Exporter:</strong> <?= escapeHtml($meta['exporter_details'] ?? '') ?></div></div><div class="table-responsive"><table class="table table-bordered"><thead><tr><th>#</th><th>Product</th><th>HS Code</th><th>Package</th><th>Qty</th><th>Net Wt</th><th>Gross Wt</th><th>Remarks</th></tr></thead><tbody><?php foreach ($items as $index => $item): ?><tr><td><?= $index + 1 ?></td><td><?= escapeHtml($item['product_name'] ?? '') ?></td><td><?= escapeHtml($item['hsn_code'] ?? '') ?></td><td><?= escapeHtml($item['packing_type_name'] ?? '') ?></td><td class="text-end"><?= number_format((float) ($item['quantity'] ?? 0), 3) ?></td><td class="text-end"><?= number_format((float) ($item['net_weight'] ?? 0), 3) ?></td><td class="text-end"><?= number_format((float) ($item['gross_weight'] ?? 0), 3) ?></td><td><?= escapeHtml($item['item_remarks'] ?? '') ?></td></tr><?php endforeach; ?></tbody></table></div><div><strong>Remarks:</strong><br><?= nl2br(escapeHtml($shippingBill['remarks'] ?? '')) ?></div></div></div>
<div class="row mt-3 no-print"><div class="col-md-6"><div class="card"><div class="card-body"><h5>Revision History</h5><?php foreach ($revisions as $revision): ?><div>Rev <?= (int) $revision['revision_number'] ?> - <?= escapeHtml($revision['created_at']) ?> - <?= escapeHtml($revision['revision_notes'] ?? '') ?></div><?php endforeach; ?><form method="post" action="/shipping-bills/<?= (int) ($shippingBill['id'] ?? 0) ?>/revise" class="mt-2"><?= csrfToken() ?><input type="text" name="revision_notes" class="form-control mb-2" placeholder="Revision notes"><button class="btn btn-sm btn-primary">Save Revision</button></form></div></div></div><div class="col-md-6"><div class="card"><div class="card-body"><h5>Status History</h5><form method="post" action="/shipping-bills/<?= (int) ($shippingBill['id'] ?? 0) ?>/status" class="row g-2"><?= csrfToken() ?><div class="col-md-5"><select name="status" class="form-select"><?php foreach ($statuses as $statusId => $statusName): ?><option value="<?= (int) $statusId ?>" <?= (int) ($shippingBill['status'] ?? 0) === (int) $statusId ? 'selected' : '' ?>><?= escapeHtml($statusName) ?></option><?php endforeach; ?></select></div><div class="col-md-5"><input type="text" name="remarks" class="form-control" placeholder="Status remarks"></div><div class="col-md-2"><button class="btn btn-primary">Update</button></div></form><?php foreach ($history as $entry): ?><div class="small text-muted mt-1"><?= escapeHtml($entry['created_at']) ?>: <?= escapeHtml($statuses[(int) $entry['new_status']] ?? 'Unknown') ?> <?= escapeHtml($entry['remarks'] ?? '') ?></div><?php endforeach; ?></div></div></div></div>